// ***********************************************************************
// Assembly         : PersonalFinance.Common.ApplicationInsights
// Author           : David Sneider Cardona Cardenas
// Created          : 08-02-2021
//
// Last Modified By : David Sneider Cardona Cardenas
// Last Modified On : 08-02-2021
// ***********************************************************************
// <copyright file="AppSettingInfo.cs" company="PersonalFinance.Common.ApplicationInsights">
//     Copyright (c) David Cardona - Software Developer. All rights reserved.
// </copyright>
// <summary></summary>
// ***********************************************************************
using System.Diagnostics.CodeAnalysis;

namespace PersonalFinance.Common.ApplicationInsights.Dtos
{
    /// <summary>
    /// Class AppSettingInfo.
    /// </summary>
    /// <autogeneratedoc />
    /// TODO Edit XML Comment Template for AppSettingInfo
    [ExcludeFromCodeCoverage]
    public class AppSettingInfo
    {
        /// <summary>
        /// Gets or sets a value indicating whether this <see cref="AppSettingInfo"/> is enabled.
        /// </summary>
        /// <value><c>true</c> if enabled; otherwise, <c>false</c>.</value>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for Enabled
        public bool Enabled { get; set; }
        /// <summary>
        /// Gets or sets the instrumentation key.
        /// </summary>
        /// <value>The instrumentation key.</value>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for InstrumentationKey
        public string InstrumentationKey { get; set; }
    }
}
