// ***********************************************************************
// Assembly         : PersonalFinance.Common.Proxy
// Author           : David Sneider Cardona Cardenas
// Created          : 08-01-2021
//
// Last Modified By : David Sneider Cardona Cardenas
// Last Modified On : 08-01-2021
// ***********************************************************************
// <copyright file="Extensions.cs" company="PersonalFinance.Common.Proxy">
//     Copyright (c) David Cardona - Software Developer. All rights reserved.
// </copyright>
// <summary></summary>
// ***********************************************************************
using Microsoft.Extensions.DependencyInjection;
using PersonalFinance.Common.Proxy.Helpers;
using System.Diagnostics.CodeAnalysis;

namespace PersonalFinance.Common.Proxy.ServiceCollections
{
    /// <summary>
    /// Class Extensions.
    /// </summary>
    /// <autogeneratedoc />
    /// TODO Edit XML Comment Template for Extensions
    [ExcludeFromCodeCoverage]
    public static class Extensions
    {
        /// <summary>
        /// Adds the proxy HTTP.
        /// </summary>
        /// <param name="services">The services.</param>
        /// <returns>IServiceCollection.</returns>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for AddProxyHttp
        public static IServiceCollection AddProxyHttp(this IServiceCollection services)
        {
            services.AddSingleton<IHttpClientHelper, HttpClientHelper>();
            return services;
        }
    }
}
