// ***********************************************************************
// Assembly         : PersonalFinance.Common.Proxy
// Author           : David Sneider Cardona Cardenas
// Created          : 07-31-2021
//
// Last Modified By : David Sneider Cardona Cardenas
// Last Modified On : 07-31-2021
// ***********************************************************************
// <copyright file="IHttpClientHelper.cs" company="PersonalFinance.Common.Proxy">
//     Copyright (c) David Cardona - Software Developer. All rights reserved.
// </copyright>
// <summary></summary>
// ***********************************************************************
using System.Collections.Generic;
using System.Net.Http;
using System.Threading.Tasks;

namespace PersonalFinance.Common.Proxy.Helpers
{
    /// <summary>
    /// Interface IHttpClientHelper
    /// </summary>
    /// <autogeneratedoc />
    /// TODO Edit XML Comment Template for IHttpClientHelper
    public interface IHttpClientHelper
    {
        /// <summary>
        /// Gets the string asynchronous.
        /// </summary>
        /// <param name="uri">The URI.</param>
        /// <param name="headers">The headers.</param>
        /// <param name="token">The token.</param>
        /// <returns>Task&lt;System.String&gt;.</returns>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for GetStringAsync
        Task<string> GetStringAsync(string uri, IDictionary<string, string> headers, string token = null);
        /// <summary>
        /// Posts the put asynchronous.
        /// </summary>
        /// <typeparam name="T"></typeparam>
        /// <param name="uri">The URI.</param>
        /// <param name="headers">The headers.</param>
        /// <param name="method">The method.</param>
        /// <param name="item">The item.</param>
        /// <param name="token">The token.</param>
        /// <returns>Task&lt;HttpResponseMessage&gt;.</returns>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for PostPutAsync`1
        Task<HttpResponseMessage> PostPutAsync<T>(string uri, IDictionary<string, string> headers, HttpMethod method, T item, string token = null);
        /// <summary>
        /// Deletes the asynchronous.
        /// </summary>
        /// <param name="uri">The URI.</param>
        /// <param name="headers">The headers.</param>
        /// <param name="method">The method.</param>
        /// <param name="token">The token.</param>
        /// <returns>Task&lt;HttpResponseMessage&gt;.</returns>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for DeleteAsync
        Task<HttpResponseMessage> DeleteAsync(string uri, IDictionary<string, string> headers, HttpMethod method, string token = null);
    }
}
