// ***********************************************************************
// Assembly         : PersonalFinance.Common.ApplicationInsights
// Author           : David Sneider Cardona Cardenas
// Created          : 08-02-2021
//
// Last Modified By : David Sneider Cardona Cardenas
// Last Modified On : 08-02-2021
// ***********************************************************************
// <copyright file="Extensions.cs" company="PersonalFinance.Common.ApplicationInsights">
//     Copyright (c) David Cardona - Software Developer. All rights reserved.
// </copyright>
// <summary></summary>
// ***********************************************************************
using Microsoft.Extensions.Configuration;
using System.Diagnostics.CodeAnalysis;

namespace PersonalFinance.Common.ApplicationInsights.Configuration
{
    /// <summary>
    /// Class Extensions.
    /// </summary>
    /// <autogeneratedoc />
    /// TODO Edit XML Comment Template for Extensions
    [ExcludeFromCodeCoverage]
    public static class Extensions
    {
        /// <summary>
        /// Gets the options.
        /// </summary>
        /// <typeparam name="TModel">The type of the t model.</typeparam>
        /// <param name="configuration">The configuration.</param>
        /// <param name="section">The section.</param>
        /// <returns>TModel.</returns>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for GetOptions`1
        public static TModel GetOptions<TModel>(this IConfiguration configuration, string section) where TModel : new()
        {
            var model = new TModel();

            configuration.GetSection(section).Bind(model);

            return model;
        }
    }
}
