// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PersonalFinance.Infraestructure.DataAcces.Context;

namespace PersonalFinance.Infraestructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210818202812_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PersonalFinance.Infraestructure.DataAcces.Entities.BudgetType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreationUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("DescriptionTypeBudget")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModificationUser")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK_BudgetType");

                    b.ToTable("BudgetType");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationDate = new DateTime(2021, 8, 18, 15, 28, 11, 55, DateTimeKind.Local).AddTicks(345),
                            CreationUser = "Migration",
                            Deleted = false,
                            DescriptionTypeBudget = "Mercado"
                        },
                        new
                        {
                            Id = 2,
                            CreationDate = new DateTime(2021, 8, 18, 15, 28, 11, 55, DateTimeKind.Local).AddTicks(458),
                            CreationUser = "Migration",
                            Deleted = false,
                            DescriptionTypeBudget = "Mercado diario"
                        },
                        new
                        {
                            Id = 3,
                            CreationDate = new DateTime(2021, 8, 18, 15, 28, 11, 55, DateTimeKind.Local).AddTicks(467),
                            CreationUser = "Migration",
                            Deleted = false,
                            DescriptionTypeBudget = "Pago deudas"
                        },
                        new
                        {
                            Id = 4,
                            CreationDate = new DateTime(2021, 8, 18, 15, 28, 11, 55, DateTimeKind.Local).AddTicks(470),
                            CreationUser = "Migration",
                            Deleted = false,
                            DescriptionTypeBudget = "Ahorros"
                        },
                        new
                        {
                            Id = 5,
                            CreationDate = new DateTime(2021, 8, 18, 15, 28, 11, 55, DateTimeKind.Local).AddTicks(473),
                            CreationUser = "Migration",
                            Deleted = false,
                            DescriptionTypeBudget = "Inversiones"
                        },
                        new
                        {
                            Id = 6,
                            CreationDate = new DateTime(2021, 8, 18, 15, 28, 11, 55, DateTimeKind.Local).AddTicks(492),
                            CreationUser = "Migration",
                            Deleted = false,
                            DescriptionTypeBudget = "Comidas rapidas"
                        },
                        new
                        {
                            Id = 7,
                            CreationDate = new DateTime(2021, 8, 18, 15, 28, 11, 55, DateTimeKind.Local).AddTicks(496),
                            CreationUser = "Migration",
                            Deleted = false,
                            DescriptionTypeBudget = "Vestuario"
                        },
                        new
                        {
                            Id = 8,
                            CreationDate = new DateTime(2021, 8, 18, 15, 28, 11, 55, DateTimeKind.Local).AddTicks(499),
                            CreationUser = "Migration",
                            Deleted = false,
                            DescriptionTypeBudget = "Electrodomesticos"
                        },
                        new
                        {
                            Id = 9,
                            CreationDate = new DateTime(2021, 8, 18, 15, 28, 11, 55, DateTimeKind.Local).AddTicks(503),
                            CreationUser = "Migration",
                            Deleted = false,
                            DescriptionTypeBudget = "Computador"
                        },
                        new
                        {
                            Id = 10,
                            CreationDate = new DateTime(2021, 8, 18, 15, 28, 11, 55, DateTimeKind.Local).AddTicks(510),
                            CreationUser = "Migration",
                            Deleted = false,
                            DescriptionTypeBudget = "Transporte"
                        },
                        new
                        {
                            Id = 11,
                            CreationDate = new DateTime(2021, 8, 18, 15, 28, 11, 55, DateTimeKind.Local).AddTicks(513),
                            CreationUser = "Migration",
                            Deleted = false,
                            DescriptionTypeBudget = "Salud"
                        },
                        new
                        {
                            Id = 12,
                            CreationDate = new DateTime(2021, 8, 18, 15, 28, 11, 55, DateTimeKind.Local).AddTicks(516),
                            CreationUser = "Migration",
                            Deleted = false,
                            DescriptionTypeBudget = "Arriendo"
                        });
                });

            modelBuilder.Entity("PersonalFinance.Infraestructure.DataAcces.Entities.Debt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreationUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("CreditAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("CurrentAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<DateTime>("DateUpdate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("InArrears")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModificationUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("MonthlyInterest")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<int>("NumberMonthsIntArrears")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<bool>("Paid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TermInMonths")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("ThirdPartyId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_Debt");

                    b.ToTable("Debt");
                });

            modelBuilder.Entity("PersonalFinance.Infraestructure.DataAcces.Entities.FinancialMovement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AssociatedDebtId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreationUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModificationUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("MovementDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MovementDetail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("MovementValue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.HasKey("Id")
                        .HasName("PK_FinancialMovement");

                    b.ToTable("FinancialMovement");
                });

            modelBuilder.Entity("PersonalFinance.Infraestructure.DataAcces.Entities.MonthlyBudget", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("BudgedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("BudgetTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreationUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<decimal>("ExpectedSpending")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<int>("FinancialMovementId")
                        .HasColumnType("int");

                    b.Property<decimal>("GeneratedSpending")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModificationUser")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK_MonthlyBudget");

                    b.ToTable("MonthlyBudget");
                });

            modelBuilder.Entity("PersonalFinance.Infraestructure.DataAcces.Entities.MovementType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("CreationDate")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("CreationUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("DescriptionTypeMovement")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModificationUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MovementTypeSign")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("Id")
                        .HasName("PK_MovementType");

                    b.ToTable("MovementType");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationDate = new DateTime(2021, 8, 18, 15, 28, 11, 50, DateTimeKind.Local).AddTicks(4814),
                            CreationUser = "Migration",
                            Deleted = false,
                            DescriptionTypeMovement = "Salario",
                            MovementTypeSign = 1
                        });
                });

            modelBuilder.Entity("PersonalFinance.Infraestructure.DataAcces.Entities.Saving", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreationUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("CurrentBalanceSaved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<DateTime>("DateUpdate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("InArrears")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModificationUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberMonthsIntArrears")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<decimal>("SavedInitialAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<bool>("SavingFinished")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<decimal>("SavingGoal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TermInMonths")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("ThirdPartyId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_Saving");

                    b.ToTable("Saving");
                });

            modelBuilder.Entity("PersonalFinance.Infraestructure.DataAcces.Entities.ThirdParty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreationUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModificationUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("NaturalPersona")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("Id")
                        .HasName("PK_ThirdParty");

                    b.ToTable("ThirdParty");
                });
#pragma warning restore 612, 618
        }
    }
}
